import type { FastifyInstance } from 'fastify';
import { healthRoutes } from './health';
import { namesRoutes } from './names';
import { ordersRoutes } from './orders';
import { listingsRoutes } from './listings';
import { offersRoutes } from './offers';
import { salesRoutes } from './sales';
import { activityRoutes } from './activity';
import { profilesRoutes } from './profiles';
import { authRoutes } from './auth';
import { usersRoutes } from './users';
import { watchlistRoutes } from './watchlist';
import { notificationsRoutes } from './notifications';
import { websocketRoutes } from './websocket';
import { clubsRoutes } from './clubs';
import { votesRoutes } from './votes';
import { searchRoutes } from './search';
import { verificationRoutes } from './verification';
import { trendingRoutes } from './trending';
import { recommendationsRoutes } from './recommendations';
import { analyticsRoutes } from './analytics';
import { userInsightsRoutes } from './user-insights';
import { cartRoutes } from './cart';
import { poapRoutes } from './poap';
import { legendsRoutes } from './legends';
import { brokeredListingsRoutes } from './brokered-listings';
import { chartsRoutes } from './charts';
import { subgraphRoutes } from './subgraph';
import { leaderboardRoutes } from './leaderboard';
import { awardsLeaderboardRoutes } from './awards-leaderboard';
import { ensRolesRoutes } from './ens-roles';
import { aiRecommendationsRoutes } from './ai-recommendations';
import { aiSearchRoutes, aiRelatedSearchRoutes } from './ai-search';
import { googleMetricsRoutes } from './google-metrics';
import { personasRoutes } from './personas';
import { adminRoutes } from './admin';
import { broadcastImagesRoutes } from './broadcast-images';
import { chatsRoutes } from './chats';
import { blocksRoutes } from './blocks';
import { commentsRoutes } from './comments';

export function registerRoutes(fastify: FastifyInstance) {
  fastify.register(healthRoutes, { prefix: '/health' });
  fastify.register(authRoutes, { prefix: '/api/v1/auth' });
  fastify.register(usersRoutes, { prefix: '/api/v1/users' });
  fastify.register(verificationRoutes, { prefix: '/api/v1/verification' });
  fastify.register(watchlistRoutes, { prefix: '/api/v1/watchlist' });
  fastify.register(notificationsRoutes, { prefix: '/api/v1/notifications' });
  fastify.register(votesRoutes, { prefix: '/api/v1/votes' });
  fastify.register(searchRoutes, { prefix: '/api/v1/search' });
  fastify.register(cartRoutes, { prefix: '/api/v1/cart' });
  fastify.register(poapRoutes, { prefix: '/api/v1/poap' });
  fastify.register(legendsRoutes, { prefix: '/api/v1/legends' });
  fastify.register(namesRoutes, { prefix: '/api/v1/names' });
  fastify.register(ordersRoutes, { prefix: '/api/v1/orders' });
  fastify.register(listingsRoutes, { prefix: '/api/v1/listings' });
  fastify.register(brokeredListingsRoutes, { prefix: '/api/v1/brokered-listings' });
  fastify.register(offersRoutes, { prefix: '/api/v1/offers' });
  fastify.register(salesRoutes, { prefix: '/api/v1/sales' });
  fastify.register(activityRoutes, { prefix: '/api/v1/activity' });
  fastify.register(profilesRoutes, { prefix: '/api/v1/profiles' });
  fastify.register(clubsRoutes, { prefix: '/api/v1/clubs' });
  fastify.register(leaderboardRoutes, { prefix: '/api/v1/leaderboard' });
  fastify.register(awardsLeaderboardRoutes, { prefix: '/api/v1/awards-leaderboard' });
  fastify.register(trendingRoutes, { prefix: '/api/v1/trending' });
  fastify.register(recommendationsRoutes, { prefix: '/api/v1/recommendations' });
  fastify.register(analyticsRoutes, { prefix: '/api/v1/analytics' });
  fastify.register(chartsRoutes, { prefix: '/api/v1/charts' });
  fastify.register(userInsightsRoutes, { prefix: '/api/v1/user' });
  fastify.register(subgraphRoutes, { prefix: '/api/v1/subgraph' });
  fastify.register(ensRolesRoutes, { prefix: '/api/v1/ens-roles' });
  fastify.register(aiRecommendationsRoutes, { prefix: '/api/v1/ai-recommendations' });
  fastify.register(aiSearchRoutes, { prefix: '/api/v1/ai/search/semantic' });
  fastify.register(aiRelatedSearchRoutes, { prefix: '/api/v1/ai/search/related' });
  fastify.register(googleMetricsRoutes, { prefix: '/api/v1/google-metrics' });
  fastify.register(personasRoutes, { prefix: '/api/v1/personas' });
  fastify.register(adminRoutes, { prefix: '/api/v1/admin' });
  fastify.register(broadcastImagesRoutes, { prefix: '/api/v1/broadcasts/images' });
  fastify.register(chatsRoutes, { prefix: '/api/v1/chats' });
  fastify.register(blocksRoutes, { prefix: '/api/v1/me/blocks' });
  fastify.register(commentsRoutes, { prefix: '/api/v1/comments' });
  fastify.register(websocketRoutes, { prefix: '/ws' });
}