-- Migration: 0460_create_ai_recommendations
-- Description: Create ai_recommendations table to cache AI-generated similar name suggestions
-- These are generated by OpenAI and cached with a TTL to avoid repeated API calls

CREATE TABLE ai_recommendations (
    id SERIAL PRIMARY KEY,

    -- Label only, no .eth suffix (e.g. 'vitalik', not 'vitalik.eth')
    -- No foreign key to ens_names — works for unregistered names too
    name VARCHAR(255) NOT NULL,

    -- Array of recommended name labels, e.g. ["adam","aaron","alex"]
    recommendations JSONB NOT NULL,

    -- OpenAI model used to generate these recommendations
    model TEXT NOT NULL,

    -- Cache TTL — recommendations expire after this timestamp
    expires_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- One cached result per name
    CONSTRAINT unique_ai_recommendation_name UNIQUE (name)
);

-- Index for cache lookup: find by name (covered by unique constraint)
-- Index for cache expiry cleanup
CREATE INDEX idx_ai_recommendations_expires_at ON ai_recommendations(expires_at);

-- Add comments for documentation
COMMENT ON TABLE ai_recommendations IS 'Caches AI-generated similar name suggestions from OpenAI';
COMMENT ON COLUMN ai_recommendations.name IS 'ENS label only (no .eth suffix), e.g. vitalik';
COMMENT ON COLUMN ai_recommendations.recommendations IS 'JSON array of recommended name labels, e.g. ["adam","aaron"]';
COMMENT ON COLUMN ai_recommendations.model IS 'OpenAI model name used for generation, e.g. gpt-5.2-2025-12-11';
COMMENT ON COLUMN ai_recommendations.expires_at IS 'Cache expiry timestamp (7 days from generation)';
