-- Migration: 0490_create_ai_search_expansions
-- Description: Create ai_search_expansions table to cache AI-generated semantic search expansions
-- These are generated by OpenAI and cached with a 30-day TTL to avoid repeated API calls

CREATE TABLE ai_search_expansions (
    id SERIAL PRIMARY KEY,

    -- Normalized search query (lowercase, trimmed)
    query VARCHAR(255) NOT NULL,

    -- Array of ~100 semantically associated words
    expansions JSONB NOT NULL,

    -- OpenAI model used to generate these expansions
    model TEXT NOT NULL,

    -- Cache TTL — expansions expire after this timestamp (30 days)
    expires_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- One cached result per query
    CONSTRAINT unique_ai_search_expansion_query UNIQUE (query)
);

-- Index for cache expiry cleanup
CREATE INDEX idx_ai_search_expansions_expires_at ON ai_search_expansions(expires_at);
